version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
    environment:
      NODE_ENV: development
  ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    container_name: ui
    stdin_open: true
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules
